### ISSUE TITLE
[Roadmap] LiteMultiAgent Roadmap Q4 2024

### ISSUE THREAD

**Issue by TataKKKL** [PathOnAI-org/LiteMultiAgent#80]
LiteMultiAgent V2 release

## 1. Allow LLM to generate and register function as tool
- [x] https://github.com/PathOnAI/LiteMultiAgent/issues/61
- [ ] bash version of create_or_update_tool
- [ ] add create_or_update_tool as a base tool to the agent, directly modify tool list

## 2. Examples for Paper
- [ ] https://github.com/PathOnAI/LiteMultiAgent/issues/73
- [ ] https://github.com/PathOnAI/LiteMultiAgent/issues/75
- [ ] https://github.com/PathOnAI/LiteMultiAgent/issues/69

## 3. Memory
- [ ] agent memory
- [ ] shared memory

## 4. Planning
- [x] https://github.com/PathOnAI/LiteMultiAgent/issues/45
- [x]  https://github.com/PathOnAI/LiteMultiAgent/pull/67

## 5. Search
- [ ] https://github.com/PathOnAI/LiteMultiAgent/issues/74

## 6. Prompt Engineering
- [ ] https://github.com/PathOnAI/LiteMultiAgent/issues/72
- [ ] pass agent_description as system prompt, https://github.com/PathOnAI/LiteMultiAgent/pull/85

## 7. Interface
- [x] multi-agent execution visualization https://github.com/PathOnAI/LiteMultiAgent/issues/32

## 8. Evaluation
- [ ] https://github.com/PathOnAI/LiteMultiAgent/issues/25
- [ ] https://github.com/PathOnAI/LiteMultiAgent/issues/71

## 9. External Agent
- [x] https://github.com/PathOnAI/LiteMultiAgent/issues/58

## 10. LiteMultiAgent writeup
- [x] https://github.com/PathOnAI/LiteMultiAgent/issues/46

## 11. Agent communication protocol
- [ ] https://github.com/PathOnAI/LiteMultiAgent/issues/54
- [x] https://github.com/PathOnAI/LiteMultiAgent/pull/83
- [x] https://github.com/PathOnAI/LiteMultiAgent/pull/84
